### ISSUE TITLE
Loading resources from unpkg

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/ucdn#2]
Thanks for the tool.

Maybe I have been missing something, but launching `ucdn` in a folder: and browsing a html resource, I see a lot of resources loaded from unpkg, not expected and not included in the html resource.

Any hint?

**Comment by WebReflection** [comment]
If the html file contains external resources, those are loaded, like it is for any CDN. It optimizes folder files, nothing else

**Comment by WebReflection** [comment]
To clarify, this is literally a CDN, nothing else.

**Comment by albertosantini** [comment]
Yep. Completely an allucination on my side.

I forgot the following import

`import { render, html } from "https://unpkg.com/uhtml?module";`

inside a js.

Sorry for the  waste of time.

**Comment by WebReflection** [comment]
Save https://unpkg.com/uhtml/index.js as source, as example, and use it as script: it’ll turned out minified and you can `const {render, html} = uhtml` instead
